[features]
seeds = false
skip-lint = false
[programs.devnet]
dblog = "4TWxkK23JiJGamgeUw4iGCf5KfRXCkobCaNxLhFXj1Ms"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/ttang/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
